apiVersion: v1
kind: Service
metadata:
  name: appointment-scheduling-service
spec:
  selector:
    app: appointment-scheduling-service
  ports:
    - protocol: TCP
      port: 51
      targetPort: 5001
  type: LoadBalancer
